#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers
source /usr/share/yunohost/helpers
source ./_common.sh

# Exit if an error occurs during the execution of the script
# ynh_abort_if_errors
ynh_abort_if_errors

domain=$YNH_APP_ARG_DOMAIN
app=$YNH_APP_INSTANCE_NAME
path='/'
is_public=$YNH_APP_ARG_IS_PUBLIC

storage_path=/home/yunohost.app/$app

# find suitable port (default 5000)
port=$(ynh_find_port 5000)

ynh_webpath_available $domain $path
if [[ ! $? -eq 0 ]]; then
  ynh_die "domain not available"
fi

# Register/book a web path for an app
ynh_webpath_register $app $domain $path


# Store Settings
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app storage_path $storage_path
ynh_app_setting_set $app port $port
ynh_app_setting_set $app path $path

installdeps

sudo mkdir $storage_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@#LOCATION#@$path@g" ../conf/nginx.conf
sed -i "s@#PORT#@$port@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

startservice $port $app $path

# Unprotect root from SSO if public
if [ "$is_public" = "1" ];
then
	ynh_app_setting_set "$app" skipped_uris "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
