#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================

app=$YNH_APP_INSTANCE_NAME
db_user=$app
db_name=$app

domain=$(ynh_app_setting_get $app domain)

sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /home/yunohost.app/$app/

docker stop $app
docker rm $app

sudo service nginx reload
sudo yunohost app ssowatconf
